### ISSUE TITLE
Why you deleted PleaseSleep?

### ISSUE THREAD

**Issue by sstyle** [Kevin-De-Koninck/TerraPi#1]
It was amazing project and it helps a lot of people. Why you deleted it?

p.s. sorry, do not know others method to contact you.

**Comment by Kevin-De-Koninck** [comment]
Yes, I'm sorry that I deleted it. But I've the code on [my website](https://kevindekoninck.com/portfolio-item/pleasesleep/). At the bottom of the post, you'll find a link to the latest source code. If you have any questions, you can add a comment on that post.

PS: I do not have ads on my website (just a plain and simple blog post).

**Comment by sstyle** [comment]
I alreay found that and replied you there. Thanks!
